version: 2
jobs:
  test:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t q-yq/android-ndk .

workflows:
  version: 2
  perfs:
    jobs:
      - test